apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu-sshd
spec:
  hostNetwork: true
  containers:
  - name: ubuntu-sshd
    image: rastasheep/ubuntu-sshd:14.04
    ports:
    - containerPort: 22
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
      limits:
        cpu: 100m
        memory: 40Mi
